name: Deploy Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run simple test
        run: |
          test -f index.html

      - name: Проверка кнопки
        run: |
          grep '<button[^>]*id="colorBtn"' index.html
          if [ $? -ne 0 ]; then
            echo "Кнопка не найдена"
            exit 1
          else
            echo "Кнопка есть - тест пройден"
          fi

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID || '' }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
